"""
===========================================================
VIP DIGIT RECOGNITION WEB APPLICATION
===========================================================

Course      : CDS6334 – Visual Information Processing (VIP)
Project     : Handwritten Digit Recognition using VIP Techniques
Application : Streamlit Web App (Frontend + Inference)

Group       : Group 2

Team Members:
1. Venggadanaathan A/L K.Salvam - 1231303562
2. Yasha Durgashine - 1221308310
3. Pavithira Saravanan - 1211110400
4. Tharraniah Tamilwanan - 1211111799
-----------------------------------------------------------
PROJECT DESCRIPTION
-----------------------------------------------------------
This Streamlit application performs handwritten digit recognition
using ONLY classical Visual Information Processing (VIP) techniques.

The system does NOT use:
- Deep Learning
- Neural Networks
- Machine Learning classifiers

Instead, it uses:
- Gaussian smoothing
- Otsu thresholding
- Morphological operations
- Distance transform + watershed segmentation
- MNIST-style normalization
- Prototype template matching using Mean Squared Error (MSE)

-----------------------------------------------------------
DATASET
-----------------------------------------------------------
- MNIST handwritten digit dataset (28x28 grayscale)
- IDX format files
- Prototypes generated offline using:
  `mnist_digit_recognition.ipynb`

-----------------------------------------------------------
SYSTEM WORKFLOW
-----------------------------------------------------------
1. User uploads an image (single or multiple digits)
2. Image is converted to grayscale
3. Digits are segmented using VIP techniques
4. Each digit is normalized to MNIST style (28x28)
5. Prototype template matching is applied
6. Recognized digits are displayed left-to-right

-----------------------------------------------------------
IMPORTANT FILE DEPENDENCY
-----------------------------------------------------------
This app requires the following file to exist:

results/prototypes_K8.npz

This file is generated by running the notebook:
`mnist_digit_recognition.ipynb`

-----------------------------------------------------------
HOW TO RUN
-----------------------------------------------------------
From the project root directory:

    streamlit run app/app.py

-----------------------------------------------------------
NOTE
-----------------------------------------------------------
This application is intended for academic demonstration
and learning purposes under the VIP course.

===========================================================
"""

import os
import numpy as np
import streamlit as st
import cv2
import matplotlib.pyplot as plt

# -----------------------------
# Paths
# -----------------------------
BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RESULTS_DIR = os.path.join(BASE_DIR, "results")
os.makedirs(RESULTS_DIR, exist_ok=True)

PROTOTYPES_PATH = os.path.join(RESULTS_DIR, "prototypes_K8.npz")

# -----------------------------
# VIP helpers
# -----------------------------
def mse(a, b):
    return float(np.mean((a - b) ** 2))

def gaussian_blur(img, ksize=3):
    img_u8 = (img * 255).astype(np.uint8)
    out = cv2.GaussianBlur(img_u8, (ksize, ksize), sigmaX=0)
    return out.astype(np.float32) / 255.0

def otsu_binarize_u8(img_float01):
    img_u8 = (img_float01 * 255).astype(np.uint8)
    _, bw = cv2.threshold(img_u8, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    return bw

def morph_close_u8(bw_u8, k=2):
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (k, k))
    return cv2.morphologyEx(bw_u8, cv2.MORPH_CLOSE, kernel)

def mnist_style_normalize(img_28, blur_ksize=3, morph_k=2):
    sm = gaussian_blur(img_28, ksize=blur_ksize)
    bw = otsu_binarize_u8(sm)
    bw = morph_close_u8(bw, k=morph_k)

    ys, xs = np.where(bw > 0)
    if len(xs) == 0 or len(ys) == 0:
        return img_28

    x0, x1 = xs.min(), xs.max()
    y0, y1 = ys.min(), ys.max()
    digit = bw[y0:y1+1, x0:x1+1]

    h, w = digit.shape
    scale = 20.0 / max(h, w)
    new_w = max(1, int(round(w * scale)))
    new_h = max(1, int(round(h * scale)))
    digit = cv2.resize(digit, (new_w, new_h), interpolation=cv2.INTER_AREA)

    canvas = np.zeros((28, 28), dtype=np.uint8)
    y_off = (28 - new_h) // 2
    x_off = (28 - new_w) // 2
    canvas[y_off:y_off+new_h, x_off:x_off+new_w] = digit

    M = cv2.moments(canvas)
    if M["m00"] != 0:
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
        shift_x = 14 - cx
        shift_y = 14 - cy
        T = np.float32([[1, 0, shift_x], [0, 1, shift_y]])
        canvas = cv2.warpAffine(canvas, T, (28, 28), borderValue=0)

    return (canvas / 255.0).astype(np.float32)

# -----------------------------
# Prototypes loading
# -----------------------------
@st.cache_resource
def load_prototypes_npz(path):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Missing {path}. Run the notebook to save results/prototypes_K8.npz first."
        )
    npz = np.load(path)
    prototypes = {d: npz[f"digit_{d}"].astype(np.float32) for d in range(10)}
    return prototypes

def predict_prototype(img_28_norm, prototypes):
    best_digit = None
    best_score = 1e9
    for d in range(10):
        for p in prototypes[d]:
            s = mse(img_28_norm, p)
            if s < best_score:
                best_score = s
                best_digit = d
    return best_digit, best_score

# -----------------------------
# Image decoding & segmentation (multi-digit)
# -----------------------------
def decode_image_to_gray(uploaded_file):
    file_bytes = np.frombuffer(uploaded_file.getvalue(), dtype=np.uint8)
    img = cv2.imdecode(file_bytes, cv2.IMREAD_GRAYSCALE)
    return img

def ensure_digit_bright_on_dark(gray_u8):
    if gray_u8.mean() > 127:
        gray_u8 = 255 - gray_u8
    return gray_u8

def segment_digits_watershed(gray_u8, min_area=60, split_strength=0.35):
    """
    Robust segmentation using Otsu + distance transform + watershed.
    Returns: bw (binary), boxes [(x,y,w,h),...]
    """
    gray_u8 = ensure_digit_bright_on_dark(gray_u8)

    # 1) Denoise
    k = int(blur_ksize)
    blur = cv2.GaussianBlur(gray_u8, (k, k), 0)

    # 2) Otsu binarization (digit = white)
    _, bw = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

    # 3) Clean small noise (opening)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
    opening = cv2.morphologyEx(bw, cv2.MORPH_OPEN, kernel, iterations=1)

    # 4) Sure background
    sure_bg = cv2.dilate(opening, kernel, iterations=2)

    # 5) Distance transform gives peaks inside digits
    dist = cv2.distanceTransform(opening, cv2.DIST_L2, 5)
    dist_norm = cv2.normalize(dist, None, 0, 1.0, cv2.NORM_MINMAX)

    # 6) Sure foreground (peaks)
    # This threshold controls splitting: higher = fewer splits, lower = more splits
    _, sure_fg = cv2.threshold(dist_norm, float(split_strength), 1.0, cv2.THRESH_BINARY)
    sure_fg = (sure_fg * 255).astype(np.uint8)

    # 7) Unknown region
    unknown = cv2.subtract(sure_bg, sure_fg)

    # 8) Marker labelling
    num_labels, markers = cv2.connectedComponents(sure_fg)
    markers = markers + 1
    markers[unknown == 255] = 0

    # 9) Watershed needs 3-channel image
    img3 = cv2.cvtColor(gray_u8, cv2.COLOR_GRAY2BGR)
    markers = cv2.watershed(img3, markers)

    # 10) Extract boxes from watershed regions
    boxes = []
    for label in range(2, num_labels + 2):  # skip background (1) and boundary (-1)
        mask = (markers == label).astype(np.uint8) * 255
        ys, xs = np.where(mask > 0)
        if len(xs) == 0 or len(ys) == 0:
            continue
        x0, x1 = xs.min(), xs.max()
        y0, y1 = ys.min(), ys.max()
        w = x1 - x0 + 1
        h = y1 - y0 + 1
        if w * h >= min_area:
            boxes.append((x0, y0, w, h))

    boxes = sorted(boxes, key=lambda b: b[0])  # left->right
    return opening, boxes


def extract_digit_rois(gray_u8, boxes, pad=10):
    H, W = gray_u8.shape
    rois = []
    for (x, y, w, h) in boxes:
        x0 = max(0, x - pad)
        y0 = max(0, y - pad)
        x1 = min(W, x + w + pad)
        y1 = min(H, y + h + pad)
        rois.append(gray_u8[y0:y1, x0:x1].copy())
    return rois

def roi_to_28x28_float(roi_u8):
    roi_u8 = ensure_digit_bright_on_dark(roi_u8)
    roi_28 = cv2.resize(roi_u8, (28, 28), interpolation=cv2.INTER_AREA).astype(np.float32) / 255.0
    return roi_28

# -----------------------------
# UI
# -----------------------------
st.set_page_config(page_title="Handwritten Digit Reader", layout="wide")
st.title("Handwritten Digit Reader")
st.write("Upload a handwritten number image (example: **5142**) and the app will read it left → right.")
st.caption("Built using classic Visual Information Processing (VIP) + prototype template matching (no deep learning).")

with st.expander("How to get the best results"):
    st.markdown("""
- Write digits clearly
- Best results when digits are single and not touching                
- Use **dark ink** on a **plain white background**
- Write digits with **thick strokes**
- Leave a **small gap** between digits
- If digits touch, switch to **Advanced** → increase **Segmentation strength**
""")

prototypes = load_prototypes_npz(PROTOTYPES_PATH)

with st.sidebar:
    st.header("Settings")
    mode = st.radio("Mode", ["Simple", "Advanced"], index=0)

    # Defaults (always defined → prevents NameError)
    min_area = 60
    pad = 10
    blur_ksize = 3
    morph_k = 2
    split_strength = 0.35

    if mode == "Simple":
        st.caption("Simple mode is recommended for most images.")
        st.markdown("**Tip:** Write with thick strokes and leave small gaps between digits.")

    else:
        st.subheader("Digit separation")
        min_area = st.slider("Ignore tiny noise", 10, 600, 60)
        pad = st.slider("Padding around digits", 0, 30, 10)

        st.subheader("Split touching digits")
        split_strength = st.slider("Split touching digits (watershed sensitivity)", 0.20, 0.60, 0.35, 0.01)

        st.subheader("Recognition tuning")
        blur_ksize = st.select_slider("Smoothness", options=[3, 5, 7], value=3)
        morph_k = st.select_slider("Stroke clean-up", options=[1, 2, 3], value=2)

    show_steps = st.checkbox("Show processing steps (optional)", value=False)

uploaded = st.file_uploader("Upload PNG/JPG", type=["png", "jpg", "jpeg"])

if uploaded is None:
    st.info("Upload an image to start.")
    st.stop()

gray = decode_image_to_gray(uploaded)
if gray is None:
    st.error("Could not read the image.")
    st.stop()

bw2, boxes = segment_digits_watershed(gray, min_area=min_area, split_strength=split_strength)

if len(boxes) == 0:
    st.error("No digits detected. Try thicker strokes / higher contrast / larger digits.")
    if show_steps:
        st.image(gray, caption="Input (grayscale)", clamp=True)
        st.image(bw2, caption="Binary mask (Otsu + close)", clamp=True)
    st.stop()

rois = extract_digit_rois(gray, boxes, pad=pad)

pred_digits = []
scores = []
norm_digits_for_display = []

for roi in rois:
    roi_28 = roi_to_28x28_float(roi)
    norm_28 = mnist_style_normalize(roi_28, blur_ksize=int(blur_ksize), morph_k=int(morph_k))
    pred, score = predict_prototype(norm_28, prototypes)
    pred_digits.append(str(pred))
    scores.append(score)
    norm_digits_for_display.append(norm_28)

result_str = "".join(pred_digits)

preview = cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)
for (x, y, w, h), d in zip(boxes, pred_digits):
    cv2.rectangle(preview, (x, y), (x+w, y+h), (0, 255, 0), 2)
    cv2.putText(preview, d, (x, max(0, y-5)), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

col1, col2 = st.columns([1, 1])

with col1:
    st.subheader("Detected digits")
    st.image(preview, caption="Digits detected left→right", channels="BGR")
    if show_steps:
        st.image(bw2, caption="Binary mask (Otsu + close)", clamp=True)

with col2:
    st.subheader("Result")

    st.markdown("## 🧾 Recognition Result")
    st.markdown(
        f"""
        <div style="
            background-color:#f6f9fc;
            padding:20px;
            border-radius:12px;
            border:1px solid #e0e0e0;
            font-size:26px;
            text-align:center;
        ">
            Detected Number<br>
            <strong style="font-size:42px;">{result_str}</strong>
        </div>
        """,
        unsafe_allow_html=True
    )

    st.info(
        """
        **Tips for best results**
        - Write digits clearly with **thick strokes**
        - Leave a **small gap between digits**
        - Use a plain background
        - If digits touch, try **Advanced mode → Split touching digits**
        """
    )

    tab_scores, tab_steps = st.tabs(["Scores", "How it works"])

    with tab_scores:
        st.write("Per-digit matching score (lower = better):")
        for i, (d, s) in enumerate(zip(pred_digits, scores), start=1):
            st.write(f"Digit {i}: **{d}** (score: {s:.5f})")

    with tab_steps:
        if show_steps:
            st.subheader("Processing steps")
            st.image(bw2, caption="Binary image after cleaning", clamp=True)

            st.subheader("Normalized digits (28×28)")
            cols = st.columns(min(6, len(norm_digits_for_display)))
            for i, img28 in enumerate(norm_digits_for_display[:6]):
                cols[i].image(img28, caption=f"#{i+1} → {pred_digits[i]}", clamp=True)
        else:
            st.info("Enable **Show processing steps** (in sidebar) to view the processing pipeline.")




